from p4utils.mininetlib.network_API import NetworkAPI

def genrate_topo():
    net = NetworkAPI()

    # Network general options
    net.setLogLevel('info')
    net.enableCli()

    # Switch

    # edge switch
    net.addP4Switch('s1', cli_input='topo/FatTree6/rules/s1-commands.txt')
    net.addP4Switch('s2', cli_input='topo/FatTree6/rules/s2-commands.txt')
    net.addP4Switch('s3', cli_input='topo/FatTree6/rules/s3-commands.txt')
    net.addP4Switch('s4', cli_input='topo/FatTree6/rules/s4-commands.txt')
    net.addP4Switch('s5', cli_input='topo/FatTree6/rules/s5-commands.txt')
    net.addP4Switch('s6', cli_input='topo/FatTree6/rules/s6-commands.txt')
    net.addP4Switch('s7', cli_input='topo/FatTree6/rules/s7-commands.txt')
    net.addP4Switch('s8', cli_input='topo/FatTree6/rules/s8-commands.txt')
    net.addP4Switch('s9', cli_input='topo/FatTree6/rules/s9-commands.txt')
    net.addP4Switch('s10', cli_input='topo/FatTree6/rules/s10-commands.txt')
    net.addP4Switch('s11', cli_input='topo/FatTree6/rules/s11-commands.txt')
    net.addP4Switch('s12', cli_input='topo/FatTree6/rules/s12-commands.txt')
    net.addP4Switch('s13', cli_input='topo/FatTree6/rules/s13-commands.txt')
    net.addP4Switch('s14', cli_input='topo/FatTree6/rules/s14-commands.txt')
    net.addP4Switch('s15', cli_input='topo/FatTree6/rules/s15-commands.txt')
    net.addP4Switch('s16', cli_input='topo/FatTree6/rules/s16-commands.txt')
    net.addP4Switch('s17', cli_input='topo/FatTree6/rules/s17-commands.txt')
    net.addP4Switch('s18', cli_input='topo/FatTree6/rules/s18-commands.txt')

    # aggregate switch
    net.addP4Switch('s19', cli_input='topo/FatTree6/rules/s19-commands.txt')
    net.addP4Switch('s20', cli_input='topo/FatTree6/rules/s20-commands.txt')
    net.addP4Switch('s21', cli_input='topo/FatTree6/rules/s21-commands.txt')
    net.addP4Switch('s22', cli_input='topo/FatTree6/rules/s22-commands.txt')
    net.addP4Switch('s23', cli_input='topo/FatTree6/rules/s23-commands.txt')
    net.addP4Switch('s24', cli_input='topo/FatTree6/rules/s24-commands.txt')
    net.addP4Switch('s25', cli_input='topo/FatTree6/rules/s25-commands.txt')
    net.addP4Switch('s26', cli_input='topo/FatTree6/rules/s26-commands.txt')
    net.addP4Switch('s27', cli_input='topo/FatTree6/rules/s27-commands.txt')
    net.addP4Switch('s28', cli_input='topo/FatTree6/rules/s28-commands.txt')
    net.addP4Switch('s29', cli_input='topo/FatTree6/rules/s29-commands.txt')
    net.addP4Switch('s30', cli_input='topo/FatTree6/rules/s30-commands.txt')
    net.addP4Switch('s31', cli_input='topo/FatTree6/rules/s31-commands.txt')
    net.addP4Switch('s32', cli_input='topo/FatTree6/rules/s32-commands.txt')
    net.addP4Switch('s33', cli_input='topo/FatTree6/rules/s33-commands.txt')
    net.addP4Switch('s34', cli_input='topo/FatTree6/rules/s34-commands.txt')
    net.addP4Switch('s35', cli_input='topo/FatTree6/rules/s35-commands.txt')
    net.addP4Switch('s36', cli_input='topo/FatTree6/rules/s36-commands.txt')

    # core switch 
    net.addP4Switch('s37', cli_input='topo/FatTree6/rules/s37-commands.txt')
    net.addP4Switch('s38', cli_input='topo/FatTree6/rules/s38-commands.txt')
    net.addP4Switch('s39', cli_input='topo/FatTree6/rules/s39-commands.txt')
    net.addP4Switch('s40', cli_input='topo/FatTree6/rules/s40-commands.txt')
    net.addP4Switch('s41', cli_input='topo/FatTree6/rules/s41-commands.txt')
    net.addP4Switch('s42', cli_input='topo/FatTree6/rules/s42-commands.txt')
    net.addP4Switch('s43', cli_input='topo/FatTree6/rules/s43-commands.txt')
    net.addP4Switch('s44', cli_input='topo/FatTree6/rules/s44-commands.txt')
    net.addP4Switch('s45', cli_input='topo/FatTree6/rules/s45-commands.txt')

    net.setP4SourceAll('p4src/switch.p4')

    # Host
    net.addHost('h1')
    net.addHost('h2')
    net.addHost('h3')
    net.addHost('h4')
    net.addHost('h5')
    net.addHost('h6')
    net.addHost('h7')
    net.addHost('h8')
    net.addHost('h9')
    net.addHost('h10')
    net.addHost('h11')
    net.addHost('h12')
    net.addHost('h13')
    net.addHost('h14')
    net.addHost('h15')
    net.addHost('h16')
    net.addHost('h17')
    net.addHost('h18')
    net.addHost('h19')
    net.addHost('h20')
    net.addHost('h21')
    net.addHost('h22')
    net.addHost('h23')
    net.addHost('h24')
    net.addHost('h25')
    net.addHost('h26')
    net.addHost('h27')
    net.addHost('h28')
    net.addHost('h29')
    net.addHost('h30')
    net.addHost('h31')
    net.addHost('h32')
    net.addHost('h33')
    net.addHost('h34')
    net.addHost('h35')
    net.addHost('h36')
    net.addHost('h37')
    net.addHost('h38')
    net.addHost('h39')
    net.addHost('h40')
    net.addHost('h41')
    net.addHost('h42')
    net.addHost('h43')
    net.addHost('h44')
    net.addHost('h45')
    net.addHost('h46')
    net.addHost('h47')
    net.addHost('h48')
    net.addHost('h49')
    net.addHost('h50')
    net.addHost('h51')
    net.addHost('h52')
    net.addHost('h53')
    net.addHost('h54')


    # core Link
    net.addLink('s37', 's19')
    net.addLink('s37', 's22')
    net.addLink('s37', 's25')
    net.addLink('s37', 's28')
    net.addLink('s37', 's31')
    net.addLink('s37', 's34')

    net.addLink('s38', 's19')
    net.addLink('s38', 's22')
    net.addLink('s38', 's25')
    net.addLink('s38', 's28')
    net.addLink('s38', 's31')
    net.addLink('s38', 's34')

    net.addLink('s39', 's19')
    net.addLink('s39', 's22')
    net.addLink('s39', 's25')
    net.addLink('s39', 's28')
    net.addLink('s39', 's31')
    net.addLink('s39', 's34')

    net.addLink('s40', 's20')
    net.addLink('s40', 's23')
    net.addLink('s40', 's26')
    net.addLink('s40', 's29')
    net.addLink('s40', 's32')
    net.addLink('s40', 's35')

    net.addLink('s41', 's20')
    net.addLink('s41', 's23')
    net.addLink('s41', 's26')
    net.addLink('s41', 's29')
    net.addLink('s41', 's32')
    net.addLink('s41', 's35')

    net.addLink('s42', 's20')
    net.addLink('s42', 's23')
    net.addLink('s42', 's26')
    net.addLink('s42', 's29')
    net.addLink('s42', 's32')
    net.addLink('s42', 's35')

    net.addLink('s43', 's21')
    net.addLink('s43', 's24')
    net.addLink('s43', 's27')
    net.addLink('s43', 's30')
    net.addLink('s43', 's33')
    net.addLink('s43', 's36')

    net.addLink('s44', 's21')
    net.addLink('s44', 's24')
    net.addLink('s44', 's27')
    net.addLink('s44', 's30')
    net.addLink('s44', 's33')
    net.addLink('s44', 's36')

    net.addLink('s45', 's21')
    net.addLink('s45', 's24')
    net.addLink('s45', 's27')
    net.addLink('s45', 's30')
    net.addLink('s45', 's33')
    net.addLink('s45', 's36')

    # aggregate Link
    net.addLink('s19', 's1')
    net.addLink('s19', 's2')
    net.addLink('s19', 's3')
    net.addLink('s20', 's1')
    net.addLink('s20', 's2')
    net.addLink('s20', 's3')
    net.addLink('s21', 's1')
    net.addLink('s21', 's2')
    net.addLink('s21', 's3')

    net.addLink('s22', 's4')
    net.addLink('s22', 's5')
    net.addLink('s22', 's6')
    net.addLink('s23', 's4')
    net.addLink('s23', 's5')
    net.addLink('s23', 's6')
    net.addLink('s24', 's4')
    net.addLink('s24', 's5')
    net.addLink('s24', 's6')

    net.addLink('s25', 's7')
    net.addLink('s25', 's8')
    net.addLink('s25', 's9')
    net.addLink('s26', 's7')
    net.addLink('s26', 's8')
    net.addLink('s26', 's9')
    net.addLink('s27', 's7')
    net.addLink('s27', 's8')
    net.addLink('s27', 's9')

    net.addLink('s28', 's10')
    net.addLink('s28', 's11')
    net.addLink('s28', 's12')
    net.addLink('s29', 's10')
    net.addLink('s29', 's11')
    net.addLink('s29', 's12')
    net.addLink('s30', 's10')
    net.addLink('s30', 's11')
    net.addLink('s30', 's12')

    net.addLink('s31', 's13')
    net.addLink('s31', 's14')
    net.addLink('s31', 's15')
    net.addLink('s32', 's13')
    net.addLink('s32', 's14')
    net.addLink('s32', 's15')
    net.addLink('s33', 's13')
    net.addLink('s33', 's14')
    net.addLink('s33', 's15')

    net.addLink('s34', 's16')
    net.addLink('s34', 's17')
    net.addLink('s34', 's18')
    net.addLink('s35', 's16')
    net.addLink('s35', 's17')
    net.addLink('s35', 's18')
    net.addLink('s36', 's16')
    net.addLink('s36', 's17')
    net.addLink('s36', 's18')

    # host link
    net.addLink('s1', 'h1')
    net.addLink('s1', 'h2')
    net.addLink('s1', 'h3')
    net.addLink('s2', 'h4')
    net.addLink('s2', 'h5')
    net.addLink('s2', 'h6')
    net.addLink('s3', 'h7')
    net.addLink('s3', 'h8')
    net.addLink('s3', 'h9')
    net.addLink('s4', 'h10')
    net.addLink('s4', 'h11')
    net.addLink('s4', 'h12')
    net.addLink('s5', 'h13')
    net.addLink('s5', 'h14')
    net.addLink('s5', 'h15')
    net.addLink('s6', 'h16')
    net.addLink('s6', 'h17')
    net.addLink('s6', 'h18')
    net.addLink('s7', 'h19')
    net.addLink('s7', 'h20')
    net.addLink('s7', 'h21')
    net.addLink('s8', 'h22')
    net.addLink('s8', 'h23')
    net.addLink('s8', 'h24')
    net.addLink('s9', 'h25')
    net.addLink('s9', 'h26')
    net.addLink('s9', 'h27')
    net.addLink('s10', 'h28')
    net.addLink('s10', 'h29')
    net.addLink('s10', 'h30')
    net.addLink('s11', 'h31')
    net.addLink('s11', 'h32')
    net.addLink('s11', 'h33')
    net.addLink('s12', 'h34')
    net.addLink('s12', 'h35')
    net.addLink('s12', 'h36')
    net.addLink('s13', 'h37')
    net.addLink('s13', 'h38')
    net.addLink('s13', 'h39')
    net.addLink('s14', 'h40')
    net.addLink('s14', 'h41')
    net.addLink('s14', 'h42')
    net.addLink('s15', 'h43')
    net.addLink('s15', 'h44')
    net.addLink('s15', 'h45')
    net.addLink('s16', 'h46')
    net.addLink('s16', 'h47')
    net.addLink('s16', 'h48')
    net.addLink('s17', 'h49')
    net.addLink('s17', 'h50')
    net.addLink('s17', 'h51')
    net.addLink('s18', 'h52')
    net.addLink('s18', 'h53')
    net.addLink('s18', 'h54')


    # Assignment strategy
    net.mixed()
    # Nodes general options
    # net.enableCpuPortAll()
    # net.enablePcapDumpAll()
    # net.enableLogAll()

    # Start the network
    net.startNetwork()