from p4utils.mininetlib.network_API import NetworkAPI

class FatTree6(NetworkAPI):
    def __init__(self):
        super().__init__()
        self.setLogLevel('info')
        self.enableCli()
        # Switch
        for i in range(1, 46):
            self.addP4Switch(f's{i}', cli_input=f'topo/FatTree6/rules/s{i}-commands.txt')
        
        self.setP4SourceAll('p4src/switch.p4')

        # Host
        for i in range(1, 55):
            self.addHost(f'h{i}')

        # core Link
        self.addLink('s37', 's19')
        self.addLink('s37', 's22')
        self.addLink('s37', 's25')
        self.addLink('s37', 's28')
        self.addLink('s37', 's31')
        self.addLink('s37', 's34')

        self.addLink('s38', 's19')
        self.addLink('s38', 's22')
        self.addLink('s38', 's25')
        self.addLink('s38', 's28')
        self.addLink('s38', 's31')
        self.addLink('s38', 's34')

        self.addLink('s39', 's19')
        self.addLink('s39', 's22')
        self.addLink('s39', 's25')
        self.addLink('s39', 's28')
        self.addLink('s39', 's31')
        self.addLink('s39', 's34')

        self.addLink('s40', 's20')
        self.addLink('s40', 's23')
        self.addLink('s40', 's26')
        self.addLink('s40', 's29')
        self.addLink('s40', 's32')
        self.addLink('s40', 's35')

        self.addLink('s41', 's20')
        self.addLink('s41', 's23')
        self.addLink('s41', 's26')
        self.addLink('s41', 's29')
        self.addLink('s41', 's32')
        self.addLink('s41', 's35')

        self.addLink('s42', 's20')
        self.addLink('s42', 's23')
        self.addLink('s42', 's26')
        self.addLink('s42', 's29')
        self.addLink('s42', 's32')
        self.addLink('s42', 's35')

        self.addLink('s43', 's21')
        self.addLink('s43', 's24')
        self.addLink('s43', 's27')
        self.addLink('s43', 's30')
        self.addLink('s43', 's33')
        self.addLink('s43', 's36')

        self.addLink('s44', 's21')
        self.addLink('s44', 's24')
        self.addLink('s44', 's27')
        self.addLink('s44', 's30')
        self.addLink('s44', 's33')
        self.addLink('s44', 's36')

        self.addLink('s45', 's21')
        self.addLink('s45', 's24')
        self.addLink('s45', 's27')
        self.addLink('s45', 's30')
        self.addLink('s45', 's33')
        self.addLink('s45', 's36')

        # aggregate Link
        self.addLink('s19', 's1')
        self.addLink('s19', 's2')
        self.addLink('s19', 's3')
        self.addLink('s20', 's1')
        self.addLink('s20', 's2')
        self.addLink('s20', 's3')
        self.addLink('s21', 's1')
        self.addLink('s21', 's2')
        self.addLink('s21', 's3')

        self.addLink('s22', 's4')
        self.addLink('s22', 's5')
        self.addLink('s22', 's6')
        self.addLink('s23', 's4')
        self.addLink('s23', 's5')
        self.addLink('s23', 's6')
        self.addLink('s24', 's4')
        self.addLink('s24', 's5')
        self.addLink('s24', 's6')

        self.addLink('s25', 's7')
        self.addLink('s25', 's8')
        self.addLink('s25', 's9')
        self.addLink('s26', 's7')
        self.addLink('s26', 's8')
        self.addLink('s26', 's9')
        self.addLink('s27', 's7')
        self.addLink('s27', 's8')
        self.addLink('s27', 's9')

        self.addLink('s28', 's10')
        self.addLink('s28', 's11')
        self.addLink('s28', 's12')
        self.addLink('s29', 's10')
        self.addLink('s29', 's11')
        self.addLink('s29', 's12')
        self.addLink('s30', 's10')
        self.addLink('s30', 's11')
        self.addLink('s30', 's12')

        self.addLink('s31', 's13')
        self.addLink('s31', 's14')
        self.addLink('s31', 's15')
        self.addLink('s32', 's13')
        self.addLink('s32', 's14')
        self.addLink('s32', 's15')
        self.addLink('s33', 's13')
        self.addLink('s33', 's14')
        self.addLink('s33', 's15')

        self.addLink('s34', 's16')
        self.addLink('s34', 's17')
        self.addLink('s34', 's18')
        self.addLink('s35', 's16')
        self.addLink('s35', 's17')
        self.addLink('s35', 's18')
        self.addLink('s36', 's16')
        self.addLink('s36', 's17')
        self.addLink('s36', 's18')

        # host link
        self.addLink('s1', 'h1')
        self.addLink('s1', 'h2')
        self.addLink('s1', 'h3')
        self.addLink('s2', 'h4')
        self.addLink('s2', 'h5')
        self.addLink('s2', 'h6')
        self.addLink('s3', 'h7')
        self.addLink('s3', 'h8')
        self.addLink('s3', 'h9')
        self.addLink('s4', 'h10')
        self.addLink('s4', 'h11')
        self.addLink('s4', 'h12')
        self.addLink('s5', 'h13')
        self.addLink('s5', 'h14')
        self.addLink('s5', 'h15')
        self.addLink('s6', 'h16')
        self.addLink('s6', 'h17')
        self.addLink('s6', 'h18')
        self.addLink('s7', 'h19')
        self.addLink('s7', 'h20')
        self.addLink('s7', 'h21')
        self.addLink('s8', 'h22')
        self.addLink('s8', 'h23')
        self.addLink('s8', 'h24')
        self.addLink('s9', 'h25')
        self.addLink('s9', 'h26')
        self.addLink('s9', 'h27')
        self.addLink('s10', 'h28')
        self.addLink('s10', 'h29')
        self.addLink('s10', 'h30')
        self.addLink('s11', 'h31')
        self.addLink('s11', 'h32')
        self.addLink('s11', 'h33')
        self.addLink('s12', 'h34')
        self.addLink('s12', 'h35')
        self.addLink('s12', 'h36')
        self.addLink('s13', 'h37')
        self.addLink('s13', 'h38')
        self.addLink('s13', 'h39')
        self.addLink('s14', 'h40')
        self.addLink('s14', 'h41')
        self.addLink('s14', 'h42')
        self.addLink('s15', 'h43')
        self.addLink('s15', 'h44')
        self.addLink('s15', 'h45')
        self.addLink('s16', 'h46')
        self.addLink('s16', 'h47')
        self.addLink('s16', 'h48')
        self.addLink('s17', 'h49')
        self.addLink('s17', 'h50')
        self.addLink('s17', 'h51')
        self.addLink('s18', 'h52')
        self.addLink('s18', 'h53')
        self.addLink('s18', 'h54')


        # Asignment strategy
        
    
        self.mixed()
        # Nodes general options
        #self.enableCpuPortAll()
        #self.enablePcapDumpAll()
        #self.enableLogAll()

        # Start the self.network

    def send(self, src_host, dst_host, src_ip, dst_ip):
        dst_ip = dst_ip.split('/')[0]
        print(f"Sending：{src_host}({src_ip}) → {dst_host}({dst_ip})")
        output1 = self.net.get(dst_host).cmd('./topo/FatTree6/receive.py &')
        output2 = self.net.get(src_host).cmd('./topo/FatTree6/send.py --ip 10.0.6.16 --m tag')
        print(output1,output2)


if __name__ == '__main__':
    ft6=FatTree6()
    ft6.start_network()
